/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entities.Membresia;
import entities.Socio;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistence.MembresiaData;
import persistence.SocioData;

/**
 *
 * @author SANTIAGO
 */
public class GestionMembresia extends javax.swing.JInternalFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private MembresiaData membresiaData =new MembresiaData();
    public GestionMembresia() {
        initComponents();
        
        agregarColumnasATable();
        rellenarFilas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCPases = new javax.swing.JComboBox<>();
        jREstado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jBBuscarMem = new javax.swing.JButton();
        jBBuscarIdSocio = new javax.swing.JButton();
        jTIdmembresia = new javax.swing.JTextField();
        jTIdsocio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBNuevo = new javax.swing.JButton();
        jBRenovar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLCosto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButton1.setText("jButton1");

        jLabel1.setText("Membresia:");

        jLabel2.setText("Id Socio:");

        jLabel3.setText("Pases:");

        jLabel4.setText("Costo:");

        jLabel5.setText("Estado:");

        jCPases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "12", "20", "I" }));
        jCPases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCPasesActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jBSalir.setText("Salir");

        jBBuscarMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jBBuscarMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarMemActionPerformed(evt);
            }
        });

        jBBuscarIdSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jBBuscarIdSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarIdSocioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("MEMBRESÍA");

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        jBNuevo.setText(" Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBRenovar.setText("Renovar");

        jBEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jBEliminar.setText(" Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });

        jLCosto.setText("Precio");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym.png"))); // NOI18N
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTIdmembresia)
                                    .addComponent(jCPases, 0, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBuscarMem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jBRenovar)
                                            .addGap(106, 106, 106))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(107, 107, 107)
                                            .addComponent(jBCrear)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jBSalir)
                                        .addGap(10, 10, 10)))
                                .addGap(238, 238, 238))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTIdsocio)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLCosto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBuscarIdSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(69, 69, 69))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(56, 56, 56)
                                .addComponent(jREstado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBNuevo)
                                .addGap(31, 31, 31)
                                .addComponent(jBEliminar)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jBBuscarMem)
                    .addComponent(jTIdmembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTIdsocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarIdSocio)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jCPases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLCosto))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jREstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRenovar)
                    .addComponent(jBCrear)
                    .addComponent(jBNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBSalir)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarMemActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTIdmembresia.getText()); // Obtener el ID ingresado en el campo de texto jTMembresia

      
        Membresia membresia = membresiaData.buscarMembresia(id); // Llamar al método buscarMembresia de la clase MembresiaData

        if (membresia != null) { // Verificar que se haya encontrado la membresía
            jTIdsocio.setText(String.valueOf(membresia.getSocio().getIdSocio())); // Mostrar el ID del socio en el campo de texto jTSocio
            // Mostrar el costo en el label jLCosto

            // Comparar el estado de la membresía para seleccionar el radioButton correspondiente
            if (membresia.getEstado() == 1) {
                jREstado.setSelected(true);
            } else {
                jREstado.setSelected(false);
            }
            // Obtener la cantidad de pases de la membresía
            int canPases = membresia.getCantPases();

            // Seleccionar automáticamente la opción correspondiente en el combobox jCPases
            if (canPases == 8) {
                jCPases.setSelectedIndex(0);
                jLCosto.setText("$8.000");
            } else if (canPases == 12) {
                jCPases.setSelectedIndex(1);
                jLCosto.setText("$10.000");
            } else if (canPases == 20) {
                jCPases.setSelectedIndex(2);
                jLCosto.setText("$12.000");
            } else {
                // Manejar el caso en el que la cantidad de pases no coincida con ninguna de las opciones del combobox
                JOptionPane.showMessageDialog(this, "Cantidad de pases no válida");
            }
        } else {
            // Manejar el caso en el que no se encuentre la membresía
            JOptionPane.showMessageDialog(this, "La membresía no existe");
        }

    }//GEN-LAST:event_jBBuscarMemActionPerformed
    private void agregarColumnasATable() {
        
        model.addColumn("Id_Membresia");
        model.addColumn("Id_Socio");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("FechaFin");
        model.addColumn("CanP");
        jTable1.setModel(model);
    }
    private void rellenarFilas(){
     //  DefaultTableModel model = (DefaultTableModel) table.getModel();
       
        List<Membresia> listaMembresias = membresiaData.listarMembresia(); // Obtener la lista de membresías

        for (Membresia membresia : listaMembresias) {
            Object[] data = {
                membresia.getIdMembresia(),
                membresia.getSocio().getIdSocio(),
                membresia.getSocio().getNombreSocio(),
                membresia.getSocio().getApellidoSocio(),
                membresia.getFechaFin(),
                membresia.getCantPases()
            };
            model.addRow(data);
        }
    }
    public void limpiarTabla() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Establecer el número de filas en 0, eliminando todas las filas existentes

}
    public void comboBox() {
        int indiceSeleccionado = jCPases.getSelectedIndex();
        double costo = 0.0;

        switch (indiceSeleccionado) {
            case 0:
                costo = 8000; // Costo para 8 pases
                break;
            case 1:
                costo = 10000; // Costo para 12 pases
                break;
            case 2:
                costo = 12000; // Costo para 20 pases
                break;
            default:
                costo = 0.0; // Costo por defecto si no hay selección válida
                break;
        }

        // Actualizar el texto de jLCosto con el costo calculado
        jLCosto.setText(String.valueOf(costo));

    }
    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        
        SocioData socioData = new SocioData();
        int idSocio = Integer.parseInt(jTIdsocio.getText());

        Socio socio = socioData.buscarSocio(idSocio);

        double costo = Double.parseDouble(jLCosto.getText());
        int estado = jREstado.isSelected() ? 1 : 0; // Ternary operator para determinar el estado
        int cantidadPases = 0; // Valor por defecto
        switch (jCPases.getSelectedIndex()) {
            case 0:
                cantidadPases = 8;
                break;
            case 1:
                cantidadPases = 12;
                break;
            case 2:
                cantidadPases = 20;
                break;
    }//GEN-LAST:event_jBCrearActionPerformed
        // Obtener la fecha actual
        LocalDate fechaActual = LocalDate.now();

        // Agregar 30 días a la fecha actual
        LocalDate fechaFutura = fechaActual.plusDays(30);

        // Crear un nuevo objeto
        Membresia nuevaMembresia = new Membresia(1, socio, fechaActual, fechaFutura, cantidadPases, costo, estado);
        membresiaData.agregarMembresia(nuevaMembresia);
    }
    private void jCPasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCPasesActionPerformed
        comboBox();
    }//GEN-LAST:event_jCPasesActionPerformed

    private void jBBuscarIdSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarIdSocioActionPerformed
        limpiarTabla();
        int idSocio = Integer.parseInt(jTIdsocio.getText());
        SocioData socioData =new SocioData();
        Socio socio =socioData.buscarSocio(idSocio);
        List<Membresia> membresias = membresiaData.listarMembresiaxSocio(socio);
        
        for (Membresia membre : membresias) {
            Object[] data = {
                membre.getIdMembresia(),
                membre.getSocio().getIdSocio(),
                membre.getSocio().getNombreSocio(),
                membre.getSocio().getApellidoSocio(),
                membre.getFechaFin(),
                membre.getCantPases()
            };
            model.addRow(data);
        }
    }//GEN-LAST:event_jBBuscarIdSocioActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        limpiarTabla();
        int id = Integer.parseInt(jTIdmembresia.getText());
        membresiaData.borrarMembresia(id);
   
        rellenarFilas();
        
    }//GEN-LAST:event_jBEliminarActionPerformed
    private void limpiarCampos(){
        jTIdmembresia.setText("");
        jTIdsocio.setText("");
        jLCosto.setText("");
        jREstado.setSelected(false);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarIdSocio;
    private javax.swing.JButton jBBuscarMem;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBRenovar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCPases;
    private javax.swing.JLabel jLCosto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jREstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTIdmembresia;
    private javax.swing.JTextField jTIdsocio;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
