/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author carba
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCargaDatos = new javax.swing.JMenu();
        jMSocio = new javax.swing.JMenuItem();
        jMEntrenador = new javax.swing.JMenuItem();
        jMClase = new javax.swing.JMenuItem();
        jMAsistencia = new javax.swing.JMenuItem();
        jMGestion = new javax.swing.JMenu();
        jMConsultasClase = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        jMCargaDatos.setText("Gestion Datos");

        jMSocio.setText("Socio");
        jMSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSocioActionPerformed(evt);
            }
        });
        jMCargaDatos.add(jMSocio);

        jMEntrenador.setText("Entrenador");
        jMEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEntrenadorActionPerformed(evt);
            }
        });
        jMCargaDatos.add(jMEntrenador);

        jMClase.setText("Clase");
        jMClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMClaseActionPerformed(evt);
            }
        });
        jMCargaDatos.add(jMClase);

        jMAsistencia.setText("Asistencia");
        jMAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAsistenciaActionPerformed(evt);
            }
        });
        jMCargaDatos.add(jMAsistencia);

        jMenuBar1.add(jMCargaDatos);

        jMGestion.setText("Consultas");

        jMConsultasClase.setText("Consultas de clases");
        jMConsultasClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultasClaseActionPerformed(evt);
            }
        });
        jMGestion.add(jMConsultasClase);

        jMenuBar1.add(jMGestion);

        jMenu3.setText("Salir");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSocioActionPerformed
        escritorio.removeAll();// limpia las ventanas
        escritorio.repaint();// se redibuja el escritorio
        GestionSocios gav = new GestionSocios();// se crea una instancia de la ventana, y por defecto es invisble
        gav.setVisible(true);// colocamos que sea visible  
        gav.setLocation(10, 10);
        escritorio.add(gav);//agrego al escritorio la ventana 
        escritorio.moveToFront(gav);// traigo al frente la ventana    }  
    }//GEN-LAST:event_jMSocioActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEntrenadorActionPerformed
        escritorio.removeAll();// limpia las ventanas
        escritorio.repaint();// se redibuja el escritorio
        GestionEntrenador gav = new GestionEntrenador();// se crea una instancia de la ventana, y por defecto es invisble
        gav.setVisible(true);// colocamos que sea visible  
        gav.setLocation(10, 10);
        escritorio.add(gav);//agrego al escritorio la ventana 
        escritorio.moveToFront(gav);// traigo al frente la ventana    }
    }//GEN-LAST:event_jMEntrenadorActionPerformed

    private void jMClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMClaseActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionClase gclase = new GestionClase();
        gclase.setVisible(true);
        gclase.setLocation(10, 10);
        escritorio.add(gclase);
        escritorio.moveToFront(gclase);
    }//GEN-LAST:event_jMClaseActionPerformed

    private void jMConsultasClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultasClaseActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultasClase consClase = new ConsultasClase();
        consClase.setVisible(true);
        consClase.setLocation(10, 10);
        escritorio.add(consClase);
        escritorio.moveToFront(consClase);
    }//GEN-LAST:event_jMConsultasClaseActionPerformed

    private void jMAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAsistenciaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionAsistencia gAs = new GestionAsistencia();
        gAs.setVisible(true);
        gAs.setLocation(10, 10);
        escritorio.add(gAs);
        escritorio.moveToFront(gAs);
    }//GEN-LAST:event_jMAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMAsistencia;
    private javax.swing.JMenu jMCargaDatos;
    private javax.swing.JMenuItem jMClase;
    private javax.swing.JMenuItem jMConsultasClase;
    private javax.swing.JMenuItem jMEntrenador;
    private javax.swing.JMenu jMGestion;
    private javax.swing.JMenuItem jMSocio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
